site_name: Nicolae Cleju, ETTI, TUIASI

theme:

  #name: material
  name: readthedocs

  features:
    - toc.integrate
    
    - navigation.tracking
    - navigation.instant
    - navigation.sections
    - navigation.expand

markdown_extensions:
  - admonition
  - attr_list
